apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-nginx
  name: gitops-nginx
spec:
<<<<<<< HEAD
  replicas: 2
=======
  replicas: 5
>>>>>>> f1dd8db0cccdedd55ece010f950f710ae99cd629
  selector:
    matchLabels:
      app: gitops-nginx
  template:
    metadata:
      labels:
        app: gitops-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
